routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('admin.dashboard');
});

Route::get('/admin', function () {
    return view('admin.dashboard');
});

Route::resource('/admin/user','UserController');
Route::resource('/admin/profile','ProfileController');
Route::resource('/admin/article','ArticleController');
Route::resource('/admin/category','CategoryController');
Route::resource('/writer/article','WriterController')->only('create','index', 'store', 'show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    public function article(){
        return $this->hasMany('App\Article');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function index(){
        $category = Category::all();
        return view('admin.category.index', ["categories" => $category]);
    }

    public function create(){
        return view('admin.category.create');
    }

    public function store(Request $request){
        $category = Category::create($request->all());
        return redirect('/admin/category');
    }

    public function show($id){
        $category = Category::find($id);
        return view('admin.category.show', ["categories" => $category]);
    }

    public function edit($id){
        $category = Category::find($id);
        return view('admin.category.update', ["categories" => $category]);
    }

    public function update(Request $request, $id){
        $category = Category::find($id);
        $category->update($request->all());
        return redirect('/admin/category');     
    }

    public function destroy($id){
        Category::destroy($id);
        return redirect('/admin/category');
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.master')

@section('page_header')
    Add New Category
@endsection

@section('page_title')
    Add New Category
@endsection

@section('content')
    <form action="/admin/category" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Nama :</label>
            <input type="text" class="form-control" placeholder="Enter Category's Name" name="nama" id="nama">
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
        <a class="btn btn-danger" href="/admin/category" role="button">Cancel</a>
    </form>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.master')

@section('page_header')
    List Article Category
@endsection

@section('page_title')
    List Article Category
@endsection

@section('content')
    <a class="btn btn-primary" href="{{route('category.create')}}" role="button">Add New Category</a>
    <br><br>
    <table class="table table-dark table-striped center" style="width:350px;">
        <thead>
        <tr class="text-center">
            <th>No</th>
            <th>Kategori</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
            @foreach($categories as $k => $c)
                <tr class="text-center">
                    <td>{{ $k + 1 }}</td>
                    <td>{{ $c -> nama }}</td>
                    <td><a class="btn btn-sm btn-success" href="{{route('category.show', ['category' => $c->id])}}" role="button"><i class="fa fa-eye"></i> </a></td>
                    <td><a class="btn btn-sm btn-warning" href="{{route('category.edit', ['category' => $c->id])}}" role="button"><i class="fa fa-edit"></a></td>
                    <td>
                        <form action="{{route('category.destroy', ['category' => $c->id])}}" method="POST" style="display:inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" value="Delete"><i class="fa fa-trash"></i></button> 
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/category/show.blade.php
@extends('layouts.master')

@section('page_header')
    Article Related To {{$categories->nama}}
@endsection

@section('page_title')
    List Article
@endsection

@section('content')
    <table class="table table-dark table-striped">
        <thead>
            <tr class="text-center">
                <th>No</th>
                <th>Judul</th>
                <th>Penulis</th>
                <th>Kategori</th>
                <th>Created</th>
                <th>Updated</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories->article as $k => $a)
                <tr class="text-center">
                    <td>{{ $k + 1 }}</td>
                    <td>{{ $a -> judul }}</td>
                    <td>{{ $a -> profile -> nama }}</td>
                    <td>{{ $a -> category -> nama }}</td>
                    <td>{{ $a -> created_at }}</td>
                    <td>{{ $a -> updated_at }}</td>
                    <td><a class="btn btn-sm btn-success" href="{{route('article.show', ['article' => $a->id])}}" role="button"><i class="fa fa-eye"></i> </a></td>
                    <td><a class="btn btn-sm btn-warning" href="{{route('article.edit', ['article' => $a->id])}}" role="button"><i class="fa fa-edit"></a></td>
                    <td>
                        <form action="{{route('article.destroy', ['article' => $a->id])}}" method="POST" style="display:inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" value="Delete"><i class="fa fa-trash"></i></button> 
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <a class="btn btn-danger" href="/admin/category" role="button">Back</a>
@endsection

resources/views/admin/category/update.blade.php
@extends('layouts.master')

@section('page_header')
    Update Category
@endsection

@section('page_title')
    Update Category
@endsection

@section('content')
    <form action=" /admin/category/{{$categories->id}}" method="POST">
        {{csrf_field()}}
        {{method_field('PUT')}}
        <div class="form-group">
            <label for="name">Nama :</label>
            <input type="text" class="form-control" placeholder="Enter Category's Name" name="nama" id="nama" value="{{$categories -> nama}}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-danger" href="/admin/category" role="button">Cancel</a>
        </div>
    </form>
@endsection