routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('admin.dashboard');
});

Route::get('/admin', function () {
    return view('admin.dashboard');
});

Route::resource('/admin/user','UserController');
Route::resource('/admin/profile','ProfileController');
Route::resource('/admin/article','ArticleController');
Route::resource('/admin/category','CategoryController');
Route::resource('/writer/article','WriterController')->only('create','index', 'store', 'show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $guarded = [];
    
    public function user()
    {
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profile;

class ProfileController extends Controller
{
    public function index(){
        $profile = Profile::all();
        return view('admin.profile.index', ["profiles" => $profile]);
    }

    public function create(){
        return view('admin.profile.create');
    }

    public function store(Request $request){
        $profile = Profile::create($request->all());
        return redirect('/admin/profile');
    }

    public function show($id){
        $profile = Profile::find($id);
        return view('admin.profile.show', ["profiles" => $profile]);
    }

    public function edit($id){
        $profile = Profile::find($id);
        return view('admin.profile.update', ["profiles" => $profile]);
    }

    public function update(Request $request, $id){
        $profile = Profile::find($id);
        $profile->update($request->all());
        return redirect('/admin/profile');     
    }

    public function destroy($id){
        Profile::destroy($id);
        return redirect('/admin/profile');
    }
}

resources/views/admin/profile/create.blade.php
@extends('layouts.master')

@section('page_header')
    Add New User Profile
@endsection

@section('page_title')
    Add New User Profile
@endsection

@section('content')
    <form action="/admin/profile" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Nama :</label>
            <input type="text" class="form-control" placeholder="Enter Name" name="nama" id="nama">
        </div>
        <div class="form-group">
            <label for="price">Email :</label>
            <input type="text" class="form-control" placeholder="Enter Email" name="email" id="email">
        </div>
        <div class="form-group">
            <label for="price">Birth Day :</label>
            <input type="text" class="form-control" placeholder="Enter Birth Day" name="birth" id="birth">
        </div>
        <div class="form-group">
            <label for="price">Telepon :</label>
            <input type="text" class="form-control" placeholder="Enter Phone Number" name="telp" id="telp">
        </div>
        <div class="form-group">
            <label for="price">Alamat :</label>
            <input type="text" class="form-control" placeholder="Enter Address" name="alamat" id="alamat">
        </div>
        <div class="form-group">
            <label for="price">User Id :</label>
            <input type="number" class="form-control" placeholder="Enter User Id" name="user_id" id="user_id">
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
        <a class="btn btn-danger" href="/admin/profile" role="button">Cancel</a>
    </form>
@endsection

resources/views/admin/profile/index.blade.php
@extends('layouts.master')

@section('page_header')
    List Profile User
@endsection

@section('page_title')
    List Profile User
@endsection

@section('content')
    <a class="btn btn-primary" href="{{route('profile.create')}}" role="button">Add New User Profile</a>
    <br><br>
    
    <table class="table table-dark table-striped">
        <thead>
        <tr class="text-center">
            <th>No</th>
            <th>Nama</th>
            <th>Email</th>
            <th>Birthday</th>
            <th>Telepon</th>
            <th>Alamat</th>
            <th>Username</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
            @foreach($profiles as $k => $p)
                <tr class="text-center">
                    <td>{{ $k + 1 }}</td>
                    <td>{{ $p -> nama }}</td>
                    <td>{{ $p -> email }}</td>
                    <td>{{ $p -> birth }}</td>
                    <td>{{ $p -> telp }}</td>
                    <td>{{ $p -> alamat }}</td>
                    <td> {{ $p -> user -> username }} </td>
                    <td><a class="btn btn-sm btn-success" href="{{route('profile.show', ['profile' => $p->id])}}" role="button"><i class="fa fa-eye"></i> </a></td>
                    <td><a class="btn btn-sm btn-warning" href="{{route('profile.edit', ['profile' => $p->id])}}" role="button"><i class="fa fa-edit"></a></td>
                    <td>
                        <form action="{{route('profile.destroy', ['profile' => $p->id])}}" method="POST" style="display:inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" value="Delete"><i class="fa fa-trash"></i></button> 
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <p>
    </p>
@endsection

resources/views/admin/profile/show.blade.php
@extends('layouts.master')

@section('page_header')
    Detail User Profile
@endsection

@section('page_title')
    Detail User Profile
@endsection

@section('content')

    <div class="card bg-dark text-white ">
        <div class="card-header text-center">
            <h3>User Profile</h3>
        </div>
        <div class="card-body">
            <table class="table text-center">
                <tr>
                    <td>Nama</td>
                    <td></td>
                    <td>{{$profiles -> nama}}</td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td></td>
                    <td>{{$profiles -> email}}</td>
                </tr>
                <tr>
                    <td>Role</td>
                    <td></td>
                    <td>{{$profiles -> birth}}</td>
                </tr>
                <tr>
                    <td>Telepon</td>
                    <td></td>
                    <td>{{$profiles -> telp}}</td>
                </tr>
                <tr>
                    <td>Alamat</td>
                    <td></td>
                    <td>{{$profiles -> alamat}}</td>
                </tr>
                <tr>
                    <td>User Id</td>
                    <td></td>
                    <td>{{$profiles -> user -> id}}</td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td></td>
                    <td>{{$profiles -> user -> username}}</td>
                </tr>
                <tr>
                    <td>User Role</td>
                    <td></td>
                    <td>{{$profiles -> user -> role}}</td>
                </tr>
            </table>       
        </div>
    </div>
    <a class="btn btn-danger" href="/admin/user" role="button">Back</a>
    



@endsection

resources/views/admin/profile/update.blade.php
@extends('layouts.master')

@section('page_header')
    Update User Profile
@endsection

@section('page_title')
    Update User Profile
@endsection

@section('content')
    <form action=" /admin/profile/{{$profiles->id}}" method="POST">
        {{csrf_field()}}
        {{method_field('PUT')}}
        <div class="form-group">
            <label for="name">Nama :</label>
            <input type="text" class="form-control" placeholder="Enter Name" name="nama" id="nama" value="{{$profiles -> nama}}">
        </div>
        <div class="form-group">
            <label for="price">Email :</label>
            <input type="text" class="form-control" placeholder="Enter Email" name="email" id="email" value="{{$profiles -> email}}">
        </div>
        <div class="form-group">
            <label for="price">Birth Day :</label>
            <input type="text" class="form-control" placeholder="Enter Birth Day" name="birth" id="birth" value="{{$profiles -> birth}}">
        </div>
        <div class="form-group">
            <label for="price">Telepon :</label>
            <input type="text" class="form-control" placeholder="Enter Phone Number" name="telp" id="telp" value="{{$profiles -> telp}}">
        </div>
        <div class="form-group">
            <label for="price">Alamat :</label>
            <input type="text" class="form-control" placeholder="Enter Address" name="alamat" id="alamat" value="{{$profiles -> alamat}}">
        </div>
        <div class="form-group">
            <label for="price">User Id :</label>
            <input type="number" class="form-control" placeholder="Enter User Id" name="user_id" id="user_id" value="{{$profiles -> user_id}}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-danger" href="/admin/profile" role="button">Cancel</a>
        </div>
    </form>
@endsection