routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('admin.dashboard');
});

Route::get('/admin', function () {
    return view('admin.dashboard');
});

Route::resource('/admin/user','UserController');
Route::resource('/admin/profile','ProfileController');
Route::resource('/admin/article','ArticleController');
Route::resource('/admin/category','CategoryController');
Route::resource('/writer/article','WriterController')->only('create','index', 'store', 'show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne('App\Profile');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function index(){
        $user = User::all();
        return view('admin.user.index', ["users" => $user]);
    }

    public function create(){
        return view('admin.user.create');
    }

    public function store(Request $request){
        $user = User::create($request->all());
        return redirect('/admin/user');
    }

    public function show($id){
        $user = User::find($id);
        return view('admin.user.show', ["users" => $user]);
    }

    public function edit($id){
        $user = User::find($id);
        return view('admin.user.update', ["users" => $user]);
    }

    public function update(Request $request, $id){
        $user = User::find($id);
        $user->update($request->all());
        return redirect('/admin/user');     
    }

    public function destroy($id){
        User::destroy($id);
        return redirect('/admin/user');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.master')

@section('page_header')
    Add New User Account
@endsection

@section('page_title')
    Add New User Account
@endsection

@section('content')
    <form action="/admin/user" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Username :</label>
            <input type="text" class="form-control" placeholder="Enter username" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="name">Password :</label>
            <input type="password" class="form-control" placeholder="Enter password" name="password" id="password">
        </div>

        <div class="form-group">
            <label for="price">Role :</label>
            <input type="text" class="form-control" placeholder="Enter user's role" name="role" id="role">
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
        <a class="btn btn-danger" href="/admin/user" role="button">Cancel</a>
    </form>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.master')

@section('page_header')
    List User Account
@endsection

@section('page_title')
    List User Account
@endsection

@section('content')
    <a class="btn btn-primary" href="{{route('user.create')}}" role="button">Add New User</a>
    <br><br>
    
    <table class="table table-dark table-striped">
        <thead>
        <tr class="text-center">
            <th>No</th>
            <th>Username</th>
            <th>Password</th>
            <th>Role</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
            @foreach($users as $k => $u)
                <tr class="text-center">
                    <td>{{ $k + 1 }}</td>
                    <td>{{ $u -> username }}</td>
                    <td>{{ $u -> password }}</td>
                    <td>{{ $u -> role }}</td>
                    <td><a class="btn btn-sm btn-success" href="{{route('user.show', ['user' => $u->id])}}" role="button"><i class="fa fa-eye"></i> </a></td>
                    <td><a class="btn btn-sm btn-warning" href="{{route('user.edit', ['user' => $u->id])}}" role="button"><i class="fa fa-edit"></a></td>
                    <td>
                        <form action="{{route('user.destroy', ['user' => $u->id])}}" method="POST" style="display:inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" value="Delete"><i class="fa fa-trash"></i></button> 
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <p>
    </p>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.master')

@section('page_header')
    Detail User Account
@endsection

@section('page_title')
    Detail User Acoount
@endsection

@section('content')

    <div class="card bg-dark text-white ">
        <div class="card-header text-center">
            <h3>User Account</h3>
        </div>
        <div class="card-body">
            <table class="table text-center">
                <tr>
                    <td>Username</td>
                    <td></td>
                    <td>{{$users->username}}</td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td></td>
                    <td>{{$users->password}}</td>
                </tr>
                <tr>
                    <td>Role</td>
                    <td></td>
                    <td>{{$users->role}}</td>
                </tr>
                <tr>
                    <td>Nama</td>
                    <td></td>
                    <td>{{$users->profile->nama}}</td>
                </tr>
            </table>       
        </div>
    </div>
    <a class="btn btn-danger" href="/admin/user" role="button">Back</a>
    



@endsection

resources/views/admin/user/update.blade.php
@extends('layouts.master')

@section('page_header')
    Update Item
@endsection

@section('page_title')
    Update Item
@endsection

@section('content')
    <form action=" /admin/user/{{$users->id}}" method="POST">
        {{csrf_field()}}
        {{method_field('PUT')}}
        <div class="form-group">
            <label for="name">Username :</label>
            <input type="text" class="form-control" placeholder="Enter username" name="username" id="username" value="{{$users -> username}}">
        </div>
        <div class="form-group">
            <label for="name">Password :</label>
            <input type="text" class="form-control" placeholder="Enter password" name="password" id="password" value="{{$users -> password}}">
        </div>
        <div class="form-group">
            <label for="price">Role :</label>
            <input type="text" class="form-control" placeholder="Enter user's role" name="role" id="role" value="{{$users -> role}}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-danger" href="/admin/user" role="button">Cancel</a>
        </div>
    </form>
@endsection